package com.gruppe4.wlan_detektor.ui.Utility

enum class DIALOG_KONTEXT {
    ECHTZEITMESSUNG,
    MESSUNG_VERWALTEN,
    HOME,
    MESSUNG_HINZUFUEGEN,
    MESSUNG_BEARBEITEN,
    MESSUGSLISTE,
    MESSPUNKT_ERFASSEN,
    MESSUNG_LOESCHEN,
    VISUALISIERUNG_GRID,
    VISUALISIERUNG_DETAIL,
    VISULISIERUNG_FULLSCREEN_BILD
}