name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checke den Code aus
        uses: actions/checkout@v2

      - name: Installiere JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run Tests
        run: ./gradlew test


      - name: Build Project
        run: ./gradlew assemble